#!/usr/bin/env bash

shm_overlay_path="/etc/schroot/chroot.d/shm-overlays.conf"

if [ -e "$shm_overlay_path" ]; then
    echo "$shm_overlay_path already exists."
    exit 1
fi

sed -e 's#]#-shm]#' \
    -e 's#^\(directory=.*\)#\1\nunion-overlay-directory=/dev/shm/schroot/overlay#' \
    /etc/schroot/chroot.d/* >"$shm_overlay_path" &&
    schroot --list
