#!/usr/bin/env bash

set -e

if [ ! -d "debian" ]; then
    echo "This script should only be executed within a package's source directory, with the build artifacts (e.g., *.ppa.upload, *.changes, etc.) in the parent directory."
    exit 1
fi

rm -vf ../*.{debian.tar.xz,dsc,buildinfo,changes,ppa.upload}
rm -vf debian/files
rm -rf .pc
