#!/usr/bin/env bash

set -e

quilt pop -a 2>/dev/null || echo "No patches applied"
schroot -e --all-sessions
rm -rf /var/lib/sbuild/build/*
rm -vf ../*.{debian.tar.xz,dsc,buildinfo,changes,ppa.upload}
rm -vf debian/files
rm -rf .pc
