#!/usr/bin/env bash

set -e

quilt pop -a 2>/dev/null || echo "No patches applied"
schroot -e --all-sessions
rm -rf /var/lib/sbuild/build/reproducible-path/*
rm -vf ../*.{debian.tar.xz,dsc}
rm -rf .pc
